### ISSUE TITLE
I made a Docker server for rffmpeg

### ISSUE THREAD

**Issue by BasixKOR** [joshuaboniface/rffmpeg#15]
Ok, this isn't an issue per se but I just wanted you to know I have been able to get this running on Docker:

https://github.com/BasixKOR/rffmpeg-docker

Thank you for your great project!

**Comment by joshuaboniface** [comment]
This definitely looks cool - I'd take the Dockerfile as a PR to the repo if you're interested (note it would be relicenced as GPLv3 along with the rest of the project), perhaps under a `docker` folder. Or I can link to this, totally up to you!
