### ISSUE TITLE
New setup with Emby, getting errors...

### ISSUE THREAD

**Issue by BastionNtB** [joshuaboniface/rffmpeg#19]
Everytime Emby calls the ffmpeg, this is the error it's getting:

ssh: symbol lookup error: ssh: undefined symbol: ENGINE_register_all_complete, version OPENSSL_1_1_0

Any idea what this is? I can't seem to figure it out.

**Comment by joshuaboniface** [comment]
Looks like some problem with ssh. Try setting the path explicitly in the YAML.

**Comment by joshuaboniface** [comment]
You don't happen to be in Docker do you? It *looks* like it's trying to call `ssh` with no `$PATH` set, but whatever it's calling isn't a valid SSH binary. I do recall seeing this quite a while back from an early user; I thought there was an issue about it but I don't see it, but I do recall that being the underlying problem after a lot of testing.

**Comment by BastionNtB** [comment]
You know, I apologize I gave you no background context.

Emby is running in Ubuntu 20.04, rffmpeg is running on 22.04, non of them are dockerized.

I will try the absolute path tomorrow. 😊

**Comment by BastionNtB** [comment]
All right, so I tested it with the full path for SSH, which I got from using "which ssh", no dice.

I did try running the exact command that Emby runs via SSH from the Emby user that is being utilized by Emby itself, and I get a different error...

/home/svc_emby/bin/ffmpeg: symbol lookup error: /home/svc_emby/bin/ffmpeg: undefined symbol: avfilter_alloc, version LIBAVFILTER_7

But looking at the logs, I see the same error from before.

Here are all the log files that relate to me attempting to watch a movie after a fresh restart of Emby, so there's not too much chatter to sort through.

Among the symbol errors, I also get errors regarding not having codecs, which I don't get when I encode regularly on the server. I did end up trying to install "h264enc" on the rffmpeg encoder server, but it didn't change anything. 

If there is anyway I can help troubleshoot this, don't hesitate to ask for it, I wouldn't mind helping out in anyway I can! :)

[ffmpeg-transcode-829b172b-be1a-4a70-8c4e-5407bd1283b7_1.txt](https://github.com/joshuaboniface/rffmpeg/files/8610755/ffmpeg-transcode-829b172b-be1a-4a70-8c4e-5407bd1283b7_1.txt)
[ffmpeg-transcode-71736d9a-c0ae-4f94-bf2e-33835dcb048a_1.txt](https://github.com/joshuaboniface/rffmpeg/files/8610756/ffmpeg-transcode-71736d9a-c0ae-4f94-bf2e-33835dcb048a_1.txt)
[hardware_detection-63787155982.txt](https://github.com/joshuaboniface/rffmpeg/files/8610757/hardware_detection-63787155982.txt)
[rffmpeg.log](https://github.com/joshuaboniface/rffmpeg/files/8610758/rffmpeg.log)
[embyserver.txt](https://github.com/joshuaboniface/rffmpeg/files/8610759/embyserver.txt)
[embyserver-63787155976.txt](https://github.com/joshuaboniface/rffmpeg/files/8610760/embyserver-63787155976.txt)
[ffmpeg-directstream-3e4d5779-05f6-4c74-99d5-e76b60782704_1.txt](https://github.com/joshuaboniface/rffmpeg/files/8610761/ffmpeg-directstream-3e4d5779-05f6-4c74-99d5-e76b60782704_1.txt)
[ffmpeg-directstream-dcf75283-3b74-4215-8491-9ffcc200bcd6_1.txt](https://github.com/joshuaboniface/rffmpeg/files/8610762/ffmpeg-directstream-dcf75283-3b74-4215-8491-9ffcc200bcd6_1.txt)

**Comment by BastionNtB** [comment]
Hello again, not to be a bother, but is there anything else I can provide to help troubleshoot this? Thanks!

**Comment by Floflobel** [comment]
You can follow this issue, it's the same problem and is solved by installing openssh-portable:
https://github.com/joshuaboniface/rffmpeg/issues/10#issuecomment-848825082
