### ISSUE TITLE
Allow different path for local ffmpeg

### ISSUE THREAD

**Issue by RaymondSchnyder** [joshuaboniface/rffmpeg#2]
Hi,

Im using this project in a docker setup with 2 VMs.
One VM is the docker host (media) and one VM (transcode) has the virtual GPU attached.
Now, as mounted paths between docker host and docker container vary (jellyfin config dir on host: /var/lib/jellyfin, jellyfin config dir in the container: /config) its a bit sturdy to place the ffmpeg files.
Im using "/usr/lib/jellyfin-ffmpeg/" as path on the transcode machine right now, as this path also exists in the container, but it would be really cool if this local fallback ffmpeg were further configurable

Regards and thanks for this amazing project
Ray

**Comment by joshuaboniface** [comment]
You'd have to use symlinks to handle this as-is. I could add an option for an alternative fallback path too, but short-term a symlink to the right binary location will do the job.

**Comment by joshuaboniface** [comment]
This was fixed in dcd08f6.
