### ISSUE TITLE
Emby - rffmpeg launches but getting errors

### ISSUE THREAD

**Issue by ddscentral** [joshuaboniface/rffmpeg#20]
Hello,

After moving Emby away from main server to it's own VM, I've decided to give rffmpeg a go since the VM has no GPU access.
I can't get encoding to work. Emby logs show rffmpeg does launch and starts remote ffmpeg for transcoding, but Emby does not seem to play well with it and keeps throwing errors.
NFS is set up correctly, Emby is using the same data directory as old Emby install on the main server, transcoding temporary directory is mounted as well. All files are accessible by emby user.

Host is Ubuntu 18.04, VM is Ubuntu 22.04. Emby is version 4.6.7.0

Logs attached.

[ffmpeg-transcode-9ce0b0ba-6275-4173-b498-89091c40ea52_1.txt](https://github.com/joshuaboniface/rffmpeg/files/8686509/ffmpeg-transcode-9ce0b0ba-6275-4173-b498-89091c40ea52_1.txt)
[ffmpeg-transcode-e86321a1-ff13-4bd9-a938-9ec343f324f4_1.txt](https://github.com/joshuaboniface/rffmpeg/files/8686510/ffmpeg-transcode-e86321a1-ff13-4bd9-a938-9ec343f324f4_1.txt)
[ffmpeg-transcode-e4c3c600-56df-421f-b2c8-48933325307e_1.txt](https://github.com/joshuaboniface/rffmpeg/files/8686511/ffmpeg-transcode-e4c3c600-56df-421f-b2c8-48933325307e_1.txt)
[rffmpeg.log](https://github.com/joshuaboniface/rffmpeg/files/8686512/rffmpeg.log)
[rffmpeg.yml.txt](https://github.com/joshuaboniface/rffmpeg/files/8686532/rffmpeg.yml.txt)

[embyserver.txt](https://github.com/joshuaboniface/rffmpeg/files/8686513/embyserver.txt)

P.S. ffdetect support is added by me, it's a binary blob used by Emby to detect hardware transcoders.

**Comment by joshuaboniface** [comment]
As far as I can tell from those logs, rffmpeg is doing its part correctly and writing the output files. I can't comment on why Emby isn't reading them properly, that looks like an Emby issue.

**Comment by ddscentral** [comment]
No change with Ubuntu 20.04.
Yes, transocoding itself works, it looks more like an interaction isssue between Emby and rffmpeg. It seems Emby is not properly reading rffmpeg output.
I do not think it's purely just Emby issue. For example, it's clearly visible from the logs that remote ffmpeg does not properly quit (there's no exit code in log) and is most likely killed by a timeout.
From "good" ffmpeg logs (see below), I can see that emby normally sends the "q" letter to quit. I do not see anything like that in rffmpeg logs.
[ffmpeg-transcode-0f3fe172-e135-4b22-a449-f2d75d1b232d_1_WORKING.txt](https://github.com/joshuaboniface/rffmpeg/files/8689100/ffmpeg-transcode-0f3fe172-e135-4b22-a449-f2d75d1b232d_1_WORKING.txt)

**Comment by ddscentral** [comment]
Got to quit by wrapping ffmpeg with stdbuf. But still getting errors.
Will try Jellyfin.

**Comment by ddscentral** [comment]
Jellyfin works. Or if precisely I got it to work with a few tweaks to rffmpeg to workaround Jellyfin bugs.
I strongly suspect the main issue is not rffmpeg but NFS (or my configuration of it). While Jellyfin worked, starting playback of any video or livestream took a really long time. Switching to Samba instead of NFS fixed the issue.
Either way, this issue is not related to rffmpeg.

**Comment by joshuaboniface** [comment]
One thing I noticed while initially writing this, and didn't explicitly say but allude to in the how-to, is that NFS had to be exported from the Media server and not the Transcode server, because the software (Jellyfin in my case, but probably Emby too) was waiting on inotifies from the filesystem that do not work on an NFS client. Could that be it?

**Comment by ddscentral** [comment]
I think that's it. While looking for a solution for this issue I do remember seeing NFS inotify issue in mentioned Jellyfin forums. From what I understood it's different from the NFS locking issue described in Jellyfin docs.
Jellyfin still worked even with transcode directory exported using NFS, it just took a really long time to load videos.
My guess is Emby and Jellyfin react differently to not receiving inotifies after a certain amount of time. Jellyfin proceeds anyway to play the video but Emby throws an error instead.
