### ISSUE TITLE
Integration with linuxserver.io container

### ISSUE THREAD

**Issue by junkman690** [joshuaboniface/rffmpeg#26]
Not an issue, but integration with with the linuxserver.io container is now added https://github.com/linuxserver/docker-mods/tree/jellyfin-rffmpeg. This version also has a basic WOL wrapper option for anyone who wants to utilise it or use it as a basis for their own wrapper.

**Comment by Mavyre** [comment]
Super cool stuff! How do we open issue for that mod @junkman690? I want to try to enhance the script so it starts rffmpeg process as soon as the remote host is ready (without waiting a predefined time).

**Comment by junkman690** [comment]
You can submit a pull request directly against https://github.com/linuxserver/docker-mods/tree/jellyfin-rffmpeg and they will add it in if its suitable.
