### ISSUE TITLE
ERROR: Failed to load configuration: 'state' is missing

### ISSUE THREAD

**Issue by Ingvix** [joshuaboniface/rffmpeg#27]
Just pulled the latest changes and copied them to my system and now `sudo -u jellyfin /usr/local/bin/ffmpeg -version` outputs the error in the title but I can't figure out why. I use the default `state` so I had left it commented in the config so I uncommented it but that didn't change anything.

**Comment by Ingvix** [comment]
It writes nothing to rffmpeg.log as it seems to fail before it gets to that part. The error in the title is the only output I get.

**Comment by joshuaboniface** [comment]
Are you sure you're on both the latest code and latest config? They have to be updated together - the new config (post-`v1`) isn't compatible with the old (`v1`) code itself.

The current version has a default for the `state` value, i.e.:

https://github.com/joshuaboniface/rffmpeg/blob/master/rffmpeg#L114

So it should not throw an error like that.

**Comment by Ingvix** [comment]
Ah, I still had the old `rffmpeg.py` in `/usr/local/bin/`. I didn't realize the file extension was dropped and copying the new version didn't overwrite the old. That's solved then.

**Comment by joshuaboniface** [comment]
Excellent, that's something I was worried might happen :-)
