### ISSUE TITLE
local fallback ffmpeg honors hardware acceleration

### ISSUE THREAD

**Issue by RaymondSchnyder** [joshuaboniface/rffmpeg#3]
Im running in a particullary weird issue, if hardware acceleration is enabled, the local fallback ffmpeg is useless, because it cannot find a hardware device (on the media vm), as the device is hooked up to the transcoding vm.

**Comment by RaymondSchnyder** [comment]
Nvmd, flew over the README too fast.

**Comment by joshuaboniface** [comment]
No problem :-) Yea it's a tricky issue, there's not really a way around it due to us just passing through all the ffmpeg arguments as-is. With HWA, it's really hard to try to mangle/strip that out even in the best of circumstances.

**Comment by obsidiangroup** [comment]
As I am new to Jellyfin, and just finding this (someone pointed me towards rffmpeg via [https://features.jellyfin.org/posts/873/cluster-support] -  how are the arguments for HWA structured vs non-HWA?

**Comment by Mavyre** [comment]
I just want to point out that I wrote a little wrapper (currently in test) in the above issue. It might work with rffmpeg to remove the hardware encoding and thus, making the local fallback work with software encoding only... If you want to take a look at it or try it out, any help is appreciated. It's only based on arguments that jellyfin adds for hardware encoding.
