### ISSUE TITLE
Jellyfin Intro Skipper

### ISSUE THREAD

**Issue by aleksasiriski** [joshuaboniface/rffmpeg#33]
https://github.com/ConfusedPolarBear/intro-skipper/issues/97

**Comment by joshuaboniface** [comment]
`rffmpeg` is designed to be transparent. Are you sure the right version is present on the target machine?

If so please post full rffmpeg logs with debug enabled.

**Comment by aleksasiriski** [comment]
I'm using the fallback option, didn't add any hosts. As I see the same error with default Jellyfin ffmpeg I guess that's where the problem lies. Thanks!
