### ISSUE TITLE
Using multiple hosts at the same time?

### ISSUE THREAD

**Issue by satcom886** [joshuaboniface/rffmpeg#4]
I use rffmpeg to speed up Jellyfin on a Raspberry Pi, but none of the transcode nodes (Odroid SBCs) is not powerful enough to handle the transcode on its own.

Would it be possible to implement using multiple hosts to transcode one file?
I sort of expect the answer to be no...

**Comment by joshuaboniface** [comment]
Yea unfortunately that isn't possible - doing so would require some sort of distributed ffmpeg system that's far beyond my capabilities.

**Comment by satcom886** [comment]
Thought so. Doesn't matter. I'm still super glad that rffmpeg is a thing.

**Comment by satcom886** [comment]
I also wanted to mention I created an [Arch package](https://aur.archlinux.org/packages/rffmpeg-git/).

**Comment by joshuaboniface** [comment]
Fantastic, thanks!
