### ISSUE TITLE
What dirs do the workers really need?

### ISSUE THREAD

**Issue by aleksasiriski** [joshuaboniface/rffmpeg#47]
I want to minimize exposure to workers, it's obvious that they need transcode and subtitle extract dir, but do you happen to know what else?

This is primarily so that I can share all the required files via NFS without needing to share the Jellyfin SQLite DB, I'm working on implementing my worker docker image as a deployment on Kubernetes.

Also side question, since I know you're the leader of Jellyfin project: do you happen to know how close is Jellyfin to having external DB support? With that and rffmpeg and -noweb flag I could have a real HA setup with seperate scaling for the server, transcoding, database as well as web ui.

**Comment by joshuaboniface** [comment]
At the very least it needs those two. I'm not sure what else off-hand as I've never tried restricting it. Best to test and see what doesn't work.

There is no ETA on external DB support; it's a lot of work that still needs to be done, so we'd be talking at least a year or more and that's optimistic.

**Comment by aleksasiriski** [comment]
I'll test it and note everything it actually needs, then make a PR to README.

**Comment by aleksasiriski** [comment]
The workers only need access to the media and the transcode dir for playing said media (default is `/config/transcodes`).

rffmpeg status showing it's working:
```
rffmpeg-worker.jellyfin.svc.cluster.local  rffmpeg-workers  1   1       active  PID 396: /usr/local/bin/ffmpeg -analyzeduration 200M -f mov,mp4,m4a,3gp,3g2,mj2 -autorotate 0 -i file:/var/storage/media/test.mp4 -map_metadata -1 -map_chapters -1 -threads 0 -map 0:1 -map 0:0 -map -0:s -codec:v:0 libx264 -preset veryfast -crf 23 -maxrate 294413 -bufsize 588826 -profile:v:0 high -level 31 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 expr:gte(t,0+n_forced*3) -sc_threshold:v:0 0 -vf setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,426)/2)*2:trunc(ow/a/2)*2,format=yuv420p -codec:a:0 copy -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename /config/transcodes/04725b9d01b3db08db910f65c545a2d2%d.ts -hls_playlist_type vod -hls_list_size 0 -y /config/transcodes/04725b9d01b3db08db910f65c545a2d2.m3u8
```

I believe it's appropriate to also share the `/config/data/subtitles` directory since jellyfin uses ffmpeg to extract subtitles.

As for `/cache` or `/config/cache` dir I don't think it's necessary, I guess Jellyfin only uses that for caching metadata and posters?

**Comment by joshuaboniface** [comment]
Indeed that all seems correct to me. Good to know it's only the ones I thought!
