### ISSUE TITLE
rffmpeg breaks some Jellyfin plugins

### ISSUE THREAD

**Issue by Mavyre** [joshuaboniface/rffmpeg#56]
I found out that Jellyfin Intro Skipper broke after I started using rffmpeg. The fact that the commands output in stderr instead of stdout, except ones listed in `special_flags` may break plugins of Jellyfin analysing the media library.

In the case of Jellyfin Intro Skipper, I had to edit rffmpeg and add the `-muxers` and -`fp_format`. Would it be possible to have the  `special_flags` configurable through the config.yml file?

By the way, why is the output redirected to the stderr instead of stdout?

**Comment by joshuaboniface** [comment]
It does this because of some oddities in hiw Jellyfin parses the output. It seems completely random depending on the function. We can absolutely make it configurable.

**Comment by aleksasiriski** [comment]
I'm on it, unless @joshuaboniface wants to rather do it himself (in that case ignore my PR)

**Comment by joshuaboniface** [comment]
No problem @aleksasiriski go for it!

**Comment by joshuaboniface** [comment]
That should do it!

**Comment by Mavyre** [comment]
Awesome!
