### ISSUE TITLE
Rewrite in Go?

### ISSUE THREAD

**Issue by aleksasiriski** [joshuaboniface/rffmpeg#59]
I don't know if you have any experience in Go, but I'm just learning it and since I'm moving my hcloud-rffmpeg over to Go I thought about doing a rewrite of rffmpeg as well (it may better handle SIGFAULTS and I could possible integrate it better with my script and provide concurrency idk yet)

The goal of this question is, would you be interested in this? I know it wouldn't provide much since it's a simple wrapper script… ofcourse I can always just fork and make it my own but I would like to stay on a collaborative project, wouldn't make much sense forking if it'll stay the same and I had to maintain it by myself

**Comment by joshuaboniface** [comment]
I don't know GO much at all; I think it's definitely getting beyond the scope of what I can do. I'd encourage you to run with it though, I'm excited to see what you can do with it.

**Comment by aleksasiriski** [comment]
I'll keep you posted!

**Comment by aleksasiriski** [comment]
I'll be working on it [here](https://github.com/aleksasiriski/rffmpeg-go) and hopefully finish it in about a week
