### ISSUE TITLE
Planned features

### ISSUE THREAD

**Issue by budgierless** [joshuaboniface/rffmpeg#60]
Hi, 
Please feel free it move or close this post after this question.

I want to setup a remote media server to process my video files, and this script seems to be what is needed to make this happen.
I only issue is that this seems to only deal with ffmpeg,
Are their any plans to expand this to also add?.. for example:

FFMPEG Path | /usr/local/bin/ffmpeg | [PATH TO FFMPEG ON YOUR SERVER] |  
MPLAYER Path | /usr/local/bin/mplayer  | [PATH TO MPLAYER ON YOUR SERVER] |  
MENCODER Path | /usr/local/bin/mencoder  | [PATH TO MENCODER ON YOUR SERVER] |  
FLVTOOL2 Path | /usr/bin/flvtool2  | [PATH TO FLVTOOL2 ON YOUR SERVER] |  
MP4Box Path | /usr/local/bin/MP4Box  | [PATH TO MP4BOX ON YOUR SERVER] |  
Yamdi Path | /usr/local/bin/yamdi  | [PATH TO YAMDI ON YOUR SERVER]

Let me know
thanks

**Comment by aleksasiriski** [comment]
Check out Unmanic, it has remote hosts.

**Comment by budgierless** [comment]
No sorry, That is not what im asking, I can make the remote host myself, but in regards to your script, it is based only on ffmpeg.
But MPLAYER, MENCODER, FLVTOOL2, MP4Box and Yamdi all with with and along side ffmpeg on media servers, and i was ask if their is any chance of adding these to your script also?

**Comment by aleksasiriski** [comment]
This script is a simple SSH wrapper around FFMPEG, I myself won't be adding the features you're asking for and I don't think that Joshua will either, but he will have to confirm that.

Of course, if you end up making it yourself feel free to do a PR

**Comment by budgierless** [comment]
No problem, I hope one day its dose happen, as I am suprised that it has not been done already, but the fact that at least a ffmpeg wrapper has now been made by you guys its a major step in the right direction, as the ffmpeg is the most complex of these modules.
Thanks

**Comment by joshuaboniface** [comment]
You could probably hack in support for other arbitrary commands fairly easily., but yes, I don't plan to add any other commands as "official" commands into rffmpeg: it is fundamentally serving a specific purpose within Jellyfin et al and not really a generalized "run X command on remote server". Doing so is pretty trivial with SSH as it is, all the logic in this script is designed to ensure that ffmpeg does its thing properly due to some of its anomalies.
