### ISSUE TITLE
Enable backslash \ escaping

### ISSUE THREAD

**Issue by Mavyre** [joshuaboniface/rffmpeg#63]
Hey all,

I started using ErsatzTV using rffmpeg. So far, so good! The only issue I'm running into is that it breaks whenever I'm using space in my channel name.

The command is called with the argument: `-metadata "service_name=\"Bastflix TV\""`. This then gets translated to `-metadata "service_name="Bastflix Gaming""`. The unescaped quotes break the command call.

Is there any way to "forward" those backslashes? I dug into the code but I'm not sure where to do that.

Thank you!

**Comment by aleksasiriski** [comment]
You could change `-metadata "service_name=\"Bastflix TV\"".` to `-metadata 'service_name=\"Bastflix TV\"'.`

Or the other way around: `-metadata "service_name=\'Bastflix TV\'".`

**Comment by Mavyre** [comment]
Sure, I could. Unfortunately, that's on Ersatztv hands. I can't really change the way they do it, but I sure will open an issue on their end because their way of doing it is kinda awful.

So, I should rewrite arguments using a wrapper, you think?

**Comment by JeWe37** [comment]
Odds are this is fixed with the latest rffmpeg as #72 was merged, you should test this again.
