### ISSUE TITLE
Jellyfin in docker with docker volumes?

### ISSUE THREAD

**Issue by jimchrist-x** [joshuaboniface/rffmpeg#68]
The setup guide assumes that the data directory is at */config* and the cache at */cache*. What if I want to use docker volumes? In my situation, the config is at */var/lib/docker/volumes/jellyfin-config/_data* , the cache at */var/lib/docker/volumes/jellyfin-cache/_data* . Root privileges are required though.

**Comment by aleksasiriski** [comment]
Use [premade docker images of Jellyfin with rffmpeg preinstalled](https://github.com/aleksasiriski/rffmpeg-go), guide written here is for standard Jellyfin install.

**Comment by jimchrist-x** [comment]
Ok, thanks
