### ISSUE TITLE
RFE: HW acceleration fallback to no acceleration or per destination HW accel enabled

### ISSUE THREAD

**Issue by bugsyb** [joshuaboniface/rffmpeg#75]
Would it be possible to add a feature of disabling HW acceleration for fallback transcoding on local Jellyfin host?

Reasoning/Scenario:
Transcoding preferred host (SNUC) has HW acceleration (in my case VA-API) while the Jellyfin local system (N2) is based on SoC (no-HW accel).

When the SNUC is down ,rffmpeg will/should fallback to N2 based transcoding and what is missing at the moment to not use any HW accel.

Currently if HW accel is on, then fallback transcoding won't work. If HW accel is off, then benefits of HW accel available for 95% of time are being lost though when it's down, it doesn't become that visible to family.

Best would be to be able to get most of both worlds, by adding a function where rffmpeg would update ffmpeg command itself in case of falling back to local encoding.

If possible, and that would be preferred option, rffmpeg could test remote host (or have it statically configured at the time of adding host) and select appropriate HW accel. In this case Jellyfin side would see no HW accel configured and all would be handled/HW accel enabled at the time of rffmpeg calling remote ffmpeg.

Most of the time it is down to using appropriate ffmpeg codec switch,i.e. for VA-API h264_vaapi. (-codec:v:0 h264_vaapi).

**Comment by joshuaboniface** [comment]
No, this is not possible. It is an explicitly design goal/rule of the project to not mangle what is passed to ffmpeg. If you have HWA turned on, all hosts must support it, or it will fail on hosts that don't.
