### ISSUE TITLE
Wrong drivers being used in jellyfin?

### ISSUE THREAD

**Issue by SuspiciousDuck** [joshuaboniface/rffmpeg#80]
So, I got Jellyfin set up with rffmpeg successfully and all that. However, there's a problem with playback unfortunately. I'm running Jellyfin on an underpowered laptop, which has an Intel cpu. However, when using vaapi as a hardware accelerator, Jellyfin automatically passes through intel drivers. Checking the transcode log, it says "libva: /usr/lib/dri/i965_drv_video.so init failed" just before it fails. Is there a way to fix this? Is this a bug? I'm currently trying to install AMF, so that I won't have this problem. But it still seems significant.
Edit: This is kind of related to [issue 66](https://github.com/joshuaboniface/rffmpeg/issues/66), but this would require editing the ffmpeg arguments, because otherwise, it'll attempt to use integrated graphics on the remote computer (which I don't have).

**Comment by joshuaboniface** [comment]
You can't mix and match hardware acceleration types with `rffmpeg`. You have to pick one and all systems must support it. There is no way around this with the system as currently designed.
