### ISSUE TITLE
Suggested edit for the Setup Guide

### ISSUE THREAD

**Issue by alexneargarder** [joshuaboniface/rffmpeg#88]
Hi, I recently set up rffmpeg for JellyFin, and it's been working great, but I noticed when setting it up that the guide says this:

The important subdirectories for rffmpeg's operation are:
    transcodes/: Used to store on-the-fly transcoding files, and configurable separately in Jellyfin but with rffmpeg I recommend leaving it at the default location under the data path.

So it seems like it's saying the default transcodes path is /var/lib/jellyfin/transcodes, but for me it seems to be /var/cache/jellyfin/transcodes (I'm on Linux Mint).
This isn't a big deal but it made me think that maybe I should just point the transcodes path to the same place the guide was saying it normally is, and that worked fine for the most part. 

However, I eventually ran into an issue where the Generate Trickplay Images task was failing, and I had to do a little investigating to figure out that the reason was that it was using the /var/cache/jellyfin folder which I had avoided exporting because I changed the transcode path to not be there. So I added /var/cache/jellyfin to the paths I was exporting and now everything is working fine. This probably should have been obvious in hindsight since the guide also mentions that you need to export the cache folder, which also doesn't seem to be at /var/lib/jellyfin on Linux Mint, but I didn't realize that at the time.

Anyway, it might be a good idea to add a note to the guide that the transcodes path is at /var/cache/jellyfin/transcodes by default on Linux Mint (and probably Ubuntu I would guess?), and the cache folder is at /var/cache/jellyfin. So if someone is on those OS's they need to export /var/cache/jellyfin instead of just /var/lib/jellyfin. I'm guessing you still need /var/lib/jellyfin though because the subtitles path is there.

Thanks for making this great tool!

**Comment by joshuaboniface** [comment]
Yes I believe this was an oversight on my part. You will likely need both, or just change the transcode temp path to another path that's under `/var/lib/jellyfin` instead.
